### ISSUE TITLE
deployed project SafeOpenRoads (RoadBase)

### ISSUE THREAD

**Issue by hansvertriest** [osoc21/technical-support#25]
https://osoc-safe-open-roads.s.redpencil.io

**Comment by jbelien** [comment]
Thanks @hansvertriest !

So you're not using the droplet I provided ?
And not using `roadbase.osoc.be` ?

Is there an API ?
If so, what's the URL of your API ?

**Comment by jodiDL** [comment]
For long term deployment of the project we are using the droplet you provided: http://roadbase.osoc.be/
That server however does not have enough memory that the project needs so on that droplet we can only use a small subset to demo it.

In the short term we are using the server ABB provided us with because it has 16gb of RAM. But ABB will probably make changes on that server that might change a lot for our project, so we do still need the roadbase.osoc.be droplet :)

Everything is currently running on 1 webserver on that droplet so we have no external API (if I'm correct @juliavdkris).

**Comment by juliavdkris** [comment]
We do have an external API! It's on https://osoc-safe-open-roads.s.redpencil.io/ for the redpencil instance, and http://roadbase.osoc.be:8000/ for the droplet

**Comment by jodiDL** [comment]
> We do have an external API! It's on https://osoc-safe-open-roads.s.redpencil.io/ for the redpencil instance, and http://roadbase.osoc.be:8000/ for the droplet

Cool! Thanks!

**Comment by juliavdkris** [comment]
Whoops sorry, that first one should've been https://api.osoc-safe-open-roads.s.redpencil.io/
